# <<<  Compiler Stuff  >>>
cxx_compiler:
    - clangxx                          # [osx]
    - gxx                              # [linux]
cxx_compiler:
    - clang                            # [osx]
    - gcc                              # [linux]
target_platform:
    - osx-64                           # [osx]
    - linux-64                         # [linux]
CONDA_BUILD_SYSROOT:
    - /Users/runner/MacOSX10.9.sdk     # [osx]
cxx_compiler_version:
    - 7.3.0                            # [linux]
    - 4                                # [osx]
c_compiler_version:
    - 7.3.0                            # [linux]
    - 4                                # [osx]

# <<< Other Stuff >>>
mkl:
    - 2019.*
