#include <libtensor/gen_block_tensor/impl/gen_bto_ewmult2_impl.h>
#include "bto_ewmult2_impl.h"

namespace libtensor {


template class gen_bto_ewmult2< 0, 0, 1, bto_traits<double>, bto_ewmult2<0, 0, 1, double> >;
template class gen_bto_ewmult2< 0, 0, 2, bto_traits<double>, bto_ewmult2<0, 0, 2, double> >;
template class gen_bto_ewmult2< 0, 0, 3, bto_traits<double>, bto_ewmult2<0, 0, 3, double> >;
template class gen_bto_ewmult2< 0, 0, 4, bto_traits<double>, bto_ewmult2<0, 0, 4, double> >;
template class gen_bto_ewmult2< 0, 0, 5, bto_traits<double>, bto_ewmult2<0, 0, 5, double> >;
template class gen_bto_ewmult2< 0, 0, 6, bto_traits<double>, bto_ewmult2<0, 0, 6, double> >;
template class gen_bto_ewmult2< 0, 0, 7, bto_traits<double>, bto_ewmult2<0, 0, 7, double> >;
template class gen_bto_ewmult2< 0, 0, 8, bto_traits<double>, bto_ewmult2<0, 0, 8, double> >;

template class gen_bto_ewmult2< 0, 1, 1, bto_traits<double>, bto_ewmult2<0, 1, 1, double> >;
template class gen_bto_ewmult2< 0, 1, 2, bto_traits<double>, bto_ewmult2<0, 1, 2, double> >;
template class gen_bto_ewmult2< 0, 1, 3, bto_traits<double>, bto_ewmult2<0, 1, 3, double> >;
template class gen_bto_ewmult2< 0, 1, 4, bto_traits<double>, bto_ewmult2<0, 1, 4, double> >;
template class gen_bto_ewmult2< 0, 1, 5, bto_traits<double>, bto_ewmult2<0, 1, 5, double> >;
template class gen_bto_ewmult2< 0, 1, 6, bto_traits<double>, bto_ewmult2<0, 1, 6, double> >;
template class gen_bto_ewmult2< 0, 1, 7, bto_traits<double>, bto_ewmult2<0, 1, 7, double> >;
template class gen_bto_ewmult2< 1, 0, 1, bto_traits<double>, bto_ewmult2<1, 0, 1, double> >;
template class gen_bto_ewmult2< 1, 0, 2, bto_traits<double>, bto_ewmult2<1, 0, 2, double> >;
template class gen_bto_ewmult2< 1, 0, 3, bto_traits<double>, bto_ewmult2<1, 0, 3, double> >;
template class gen_bto_ewmult2< 1, 0, 4, bto_traits<double>, bto_ewmult2<1, 0, 4, double> >;
template class gen_bto_ewmult2< 1, 0, 5, bto_traits<double>, bto_ewmult2<1, 0, 5, double> >;
template class gen_bto_ewmult2< 1, 0, 6, bto_traits<double>, bto_ewmult2<1, 0, 6, double> >;
template class gen_bto_ewmult2< 1, 0, 7, bto_traits<double>, bto_ewmult2<1, 0, 7, double> >;

template class gen_bto_ewmult2< 0, 2, 1, bto_traits<double>, bto_ewmult2<0, 2, 1, double> >;
template class gen_bto_ewmult2< 0, 2, 2, bto_traits<double>, bto_ewmult2<0, 2, 2, double> >;
template class gen_bto_ewmult2< 0, 2, 3, bto_traits<double>, bto_ewmult2<0, 2, 3, double> >;
template class gen_bto_ewmult2< 0, 2, 4, bto_traits<double>, bto_ewmult2<0, 2, 4, double> >;
template class gen_bto_ewmult2< 0, 2, 5, bto_traits<double>, bto_ewmult2<0, 2, 5, double> >;
template class gen_bto_ewmult2< 0, 2, 6, bto_traits<double>, bto_ewmult2<0, 2, 6, double> >;
template class gen_bto_ewmult2< 1, 1, 1, bto_traits<double>, bto_ewmult2<1, 1, 1, double> >;
template class gen_bto_ewmult2< 1, 1, 2, bto_traits<double>, bto_ewmult2<1, 1, 2, double> >;
template class gen_bto_ewmult2< 1, 1, 3, bto_traits<double>, bto_ewmult2<1, 1, 3, double> >;
template class gen_bto_ewmult2< 1, 1, 4, bto_traits<double>, bto_ewmult2<1, 1, 4, double> >;
template class gen_bto_ewmult2< 1, 1, 5, bto_traits<double>, bto_ewmult2<1, 1, 5, double> >;
template class gen_bto_ewmult2< 1, 1, 6, bto_traits<double>, bto_ewmult2<1, 1, 6, double> >;
template class gen_bto_ewmult2< 2, 0, 1, bto_traits<double>, bto_ewmult2<2, 0, 1, double> >;
template class gen_bto_ewmult2< 2, 0, 2, bto_traits<double>, bto_ewmult2<2, 0, 2, double> >;
template class gen_bto_ewmult2< 2, 0, 3, bto_traits<double>, bto_ewmult2<2, 0, 3, double> >;
template class gen_bto_ewmult2< 2, 0, 4, bto_traits<double>, bto_ewmult2<2, 0, 4, double> >;
template class gen_bto_ewmult2< 2, 0, 5, bto_traits<double>, bto_ewmult2<2, 0, 5, double> >;
template class gen_bto_ewmult2< 2, 0, 6, bto_traits<double>, bto_ewmult2<2, 0, 6, double> >;

template class gen_bto_ewmult2< 0, 3, 1, bto_traits<double>, bto_ewmult2<0, 3, 1, double> >;
template class gen_bto_ewmult2< 0, 3, 2, bto_traits<double>, bto_ewmult2<0, 3, 2, double> >;
template class gen_bto_ewmult2< 0, 3, 3, bto_traits<double>, bto_ewmult2<0, 3, 3, double> >;
template class gen_bto_ewmult2< 0, 3, 4, bto_traits<double>, bto_ewmult2<0, 3, 4, double> >;
template class gen_bto_ewmult2< 0, 3, 5, bto_traits<double>, bto_ewmult2<0, 3, 5, double> >;
template class gen_bto_ewmult2< 1, 2, 1, bto_traits<double>, bto_ewmult2<1, 2, 1, double> >;
template class gen_bto_ewmult2< 1, 2, 2, bto_traits<double>, bto_ewmult2<1, 2, 2, double> >;
template class gen_bto_ewmult2< 1, 2, 3, bto_traits<double>, bto_ewmult2<1, 2, 3, double> >;
template class gen_bto_ewmult2< 1, 2, 4, bto_traits<double>, bto_ewmult2<1, 2, 4, double> >;
template class gen_bto_ewmult2< 1, 2, 5, bto_traits<double>, bto_ewmult2<1, 2, 5, double> >;
template class gen_bto_ewmult2< 2, 1, 1, bto_traits<double>, bto_ewmult2<2, 1, 1, double> >;
template class gen_bto_ewmult2< 2, 1, 2, bto_traits<double>, bto_ewmult2<2, 1, 2, double> >;
template class gen_bto_ewmult2< 2, 1, 3, bto_traits<double>, bto_ewmult2<2, 1, 3, double> >;
template class gen_bto_ewmult2< 2, 1, 4, bto_traits<double>, bto_ewmult2<2, 1, 4, double> >;
template class gen_bto_ewmult2< 2, 1, 5, bto_traits<double>, bto_ewmult2<2, 1, 5, double> >;
template class gen_bto_ewmult2< 3, 0, 1, bto_traits<double>, bto_ewmult2<3, 0, 1, double> >;
template class gen_bto_ewmult2< 3, 0, 2, bto_traits<double>, bto_ewmult2<3, 0, 2, double> >;
template class gen_bto_ewmult2< 3, 0, 3, bto_traits<double>, bto_ewmult2<3, 0, 3, double> >;
template class gen_bto_ewmult2< 3, 0, 4, bto_traits<double>, bto_ewmult2<3, 0, 4, double> >;
template class gen_bto_ewmult2< 3, 0, 5, bto_traits<double>, bto_ewmult2<3, 0, 5, double> >;

template class gen_bto_ewmult2< 0, 4, 1, bto_traits<double>, bto_ewmult2<0, 4, 1, double> >;
template class gen_bto_ewmult2< 0, 4, 2, bto_traits<double>, bto_ewmult2<0, 4, 2, double> >;
template class gen_bto_ewmult2< 0, 4, 3, bto_traits<double>, bto_ewmult2<0, 4, 3, double> >;
template class gen_bto_ewmult2< 0, 4, 4, bto_traits<double>, bto_ewmult2<0, 4, 4, double> >;
template class gen_bto_ewmult2< 1, 3, 1, bto_traits<double>, bto_ewmult2<1, 3, 1, double> >;
template class gen_bto_ewmult2< 1, 3, 2, bto_traits<double>, bto_ewmult2<1, 3, 2, double> >;
template class gen_bto_ewmult2< 1, 3, 3, bto_traits<double>, bto_ewmult2<1, 3, 3, double> >;
template class gen_bto_ewmult2< 1, 3, 4, bto_traits<double>, bto_ewmult2<1, 3, 4, double> >;
template class gen_bto_ewmult2< 2, 2, 1, bto_traits<double>, bto_ewmult2<2, 2, 1, double> >;
template class gen_bto_ewmult2< 2, 2, 2, bto_traits<double>, bto_ewmult2<2, 2, 2, double> >;
template class gen_bto_ewmult2< 2, 2, 3, bto_traits<double>, bto_ewmult2<2, 2, 3, double> >;
template class gen_bto_ewmult2< 2, 2, 4, bto_traits<double>, bto_ewmult2<2, 2, 4, double> >;
template class gen_bto_ewmult2< 3, 1, 1, bto_traits<double>, bto_ewmult2<3, 1, 1, double> >;
template class gen_bto_ewmult2< 3, 1, 2, bto_traits<double>, bto_ewmult2<3, 1, 2, double> >;
template class gen_bto_ewmult2< 3, 1, 3, bto_traits<double>, bto_ewmult2<3, 1, 3, double> >;
template class gen_bto_ewmult2< 3, 1, 4, bto_traits<double>, bto_ewmult2<3, 1, 4, double> >;
template class gen_bto_ewmult2< 4, 0, 1, bto_traits<double>, bto_ewmult2<4, 0, 1, double> >;
template class gen_bto_ewmult2< 4, 0, 2, bto_traits<double>, bto_ewmult2<4, 0, 2, double> >;
template class gen_bto_ewmult2< 4, 0, 3, bto_traits<double>, bto_ewmult2<4, 0, 3, double> >;
template class gen_bto_ewmult2< 4, 0, 4, bto_traits<double>, bto_ewmult2<4, 0, 4, double> >;

template class gen_bto_ewmult2< 0, 5, 1, bto_traits<double>, bto_ewmult2<0, 5, 1, double> >;
template class gen_bto_ewmult2< 0, 5, 2, bto_traits<double>, bto_ewmult2<0, 5, 2, double> >;
template class gen_bto_ewmult2< 0, 5, 3, bto_traits<double>, bto_ewmult2<0, 5, 3, double> >;
template class gen_bto_ewmult2< 1, 4, 1, bto_traits<double>, bto_ewmult2<1, 4, 1, double> >;
template class gen_bto_ewmult2< 1, 4, 2, bto_traits<double>, bto_ewmult2<1, 4, 2, double> >;
template class gen_bto_ewmult2< 1, 4, 3, bto_traits<double>, bto_ewmult2<1, 4, 3, double> >;
template class gen_bto_ewmult2< 2, 3, 1, bto_traits<double>, bto_ewmult2<2, 3, 1, double> >;
template class gen_bto_ewmult2< 2, 3, 2, bto_traits<double>, bto_ewmult2<2, 3, 2, double> >;
template class gen_bto_ewmult2< 2, 3, 3, bto_traits<double>, bto_ewmult2<2, 3, 3, double> >;
template class gen_bto_ewmult2< 3, 2, 1, bto_traits<double>, bto_ewmult2<3, 2, 1, double> >;
template class gen_bto_ewmult2< 3, 2, 2, bto_traits<double>, bto_ewmult2<3, 2, 2, double> >;
template class gen_bto_ewmult2< 3, 2, 3, bto_traits<double>, bto_ewmult2<3, 2, 3, double> >;
template class gen_bto_ewmult2< 4, 1, 1, bto_traits<double>, bto_ewmult2<4, 1, 1, double> >;
template class gen_bto_ewmult2< 4, 1, 2, bto_traits<double>, bto_ewmult2<4, 1, 2, double> >;
template class gen_bto_ewmult2< 4, 1, 3, bto_traits<double>, bto_ewmult2<4, 1, 3, double> >;
template class gen_bto_ewmult2< 5, 0, 1, bto_traits<double>, bto_ewmult2<5, 0, 1, double> >;
template class gen_bto_ewmult2< 5, 0, 2, bto_traits<double>, bto_ewmult2<5, 0, 2, double> >;
template class gen_bto_ewmult2< 5, 0, 3, bto_traits<double>, bto_ewmult2<5, 0, 3, double> >;

template class gen_bto_ewmult2< 0, 6, 1, bto_traits<double>, bto_ewmult2<0, 6, 1, double> >;
template class gen_bto_ewmult2< 0, 6, 2, bto_traits<double>, bto_ewmult2<0, 6, 2, double> >;
template class gen_bto_ewmult2< 1, 5, 1, bto_traits<double>, bto_ewmult2<1, 5, 1, double> >;
template class gen_bto_ewmult2< 1, 5, 2, bto_traits<double>, bto_ewmult2<1, 5, 2, double> >;
template class gen_bto_ewmult2< 2, 4, 1, bto_traits<double>, bto_ewmult2<2, 4, 1, double> >;
template class gen_bto_ewmult2< 2, 4, 2, bto_traits<double>, bto_ewmult2<2, 4, 2, double> >;
template class gen_bto_ewmult2< 3, 3, 1, bto_traits<double>, bto_ewmult2<3, 3, 1, double> >;
template class gen_bto_ewmult2< 3, 3, 2, bto_traits<double>, bto_ewmult2<3, 3, 2, double> >;
template class gen_bto_ewmult2< 4, 2, 1, bto_traits<double>, bto_ewmult2<4, 2, 1, double> >;
template class gen_bto_ewmult2< 4, 2, 2, bto_traits<double>, bto_ewmult2<4, 2, 2, double> >;
template class gen_bto_ewmult2< 5, 1, 1, bto_traits<double>, bto_ewmult2<5, 1, 1, double> >;
template class gen_bto_ewmult2< 5, 1, 2, bto_traits<double>, bto_ewmult2<5, 1, 2, double> >;
template class gen_bto_ewmult2< 6, 0, 1, bto_traits<double>, bto_ewmult2<6, 0, 1, double> >;
template class gen_bto_ewmult2< 6, 0, 2, bto_traits<double>, bto_ewmult2<6, 0, 2, double> >;

template class gen_bto_ewmult2< 0, 7, 1, bto_traits<double>, bto_ewmult2<0, 7, 1, double> >;
template class gen_bto_ewmult2< 1, 6, 1, bto_traits<double>, bto_ewmult2<1, 6, 1, double> >;
template class gen_bto_ewmult2< 2, 5, 1, bto_traits<double>, bto_ewmult2<2, 5, 1, double> >;
template class gen_bto_ewmult2< 3, 4, 1, bto_traits<double>, bto_ewmult2<3, 4, 1, double> >;
template class gen_bto_ewmult2< 4, 3, 1, bto_traits<double>, bto_ewmult2<4, 3, 1, double> >;
template class gen_bto_ewmult2< 5, 2, 1, bto_traits<double>, bto_ewmult2<5, 2, 1, double> >;
template class gen_bto_ewmult2< 6, 1, 1, bto_traits<double>, bto_ewmult2<6, 1, 1, double> >;
template class gen_bto_ewmult2< 7, 0, 1, bto_traits<double>, bto_ewmult2<7, 0, 1, double> >;


template class bto_ewmult2<0, 0, 1, double>;
template class bto_ewmult2<0, 0, 2, double>;
template class bto_ewmult2<0, 0, 3, double>;
template class bto_ewmult2<0, 0, 4, double>;
template class bto_ewmult2<0, 0, 5, double>;
template class bto_ewmult2<0, 0, 6, double>;
template class bto_ewmult2<0, 0, 7, double>;
template class bto_ewmult2<0, 0, 8, double>;
                                          
template class bto_ewmult2<0, 1, 1, double>;
template class bto_ewmult2<0, 1, 2, double>;
template class bto_ewmult2<0, 1, 3, double>;
template class bto_ewmult2<0, 1, 4, double>;
template class bto_ewmult2<0, 1, 5, double>;
template class bto_ewmult2<0, 1, 6, double>;
template class bto_ewmult2<0, 1, 7, double>;
template class bto_ewmult2<1, 0, 1, double>;
template class bto_ewmult2<1, 0, 2, double>;
template class bto_ewmult2<1, 0, 3, double>;
template class bto_ewmult2<1, 0, 4, double>;
template class bto_ewmult2<1, 0, 5, double>;
template class bto_ewmult2<1, 0, 6, double>;
template class bto_ewmult2<1, 0, 7, double>;
                                          
template class bto_ewmult2<0, 2, 1, double>;
template class bto_ewmult2<0, 2, 2, double>;
template class bto_ewmult2<0, 2, 3, double>;
template class bto_ewmult2<0, 2, 4, double>;
template class bto_ewmult2<0, 2, 5, double>;
template class bto_ewmult2<0, 2, 6, double>;
template class bto_ewmult2<1, 1, 1, double>;
template class bto_ewmult2<1, 1, 2, double>;
template class bto_ewmult2<1, 1, 3, double>;
template class bto_ewmult2<1, 1, 4, double>;
template class bto_ewmult2<1, 1, 5, double>;
template class bto_ewmult2<1, 1, 6, double>;
template class bto_ewmult2<2, 0, 1, double>;
template class bto_ewmult2<2, 0, 2, double>;
template class bto_ewmult2<2, 0, 3, double>;
template class bto_ewmult2<2, 0, 4, double>;
template class bto_ewmult2<2, 0, 5, double>;
template class bto_ewmult2<2, 0, 6, double>;
                                          
template class bto_ewmult2<0, 3, 1, double>;
template class bto_ewmult2<0, 3, 2, double>;
template class bto_ewmult2<0, 3, 3, double>;
template class bto_ewmult2<0, 3, 4, double>;
template class bto_ewmult2<0, 3, 5, double>;
template class bto_ewmult2<1, 2, 1, double>;
template class bto_ewmult2<1, 2, 2, double>;
template class bto_ewmult2<1, 2, 3, double>;
template class bto_ewmult2<1, 2, 4, double>;
template class bto_ewmult2<1, 2, 5, double>;
template class bto_ewmult2<2, 1, 1, double>;
template class bto_ewmult2<2, 1, 2, double>;
template class bto_ewmult2<2, 1, 3, double>;
template class bto_ewmult2<2, 1, 4, double>;
template class bto_ewmult2<2, 1, 5, double>;
template class bto_ewmult2<3, 0, 1, double>;
template class bto_ewmult2<3, 0, 2, double>;
template class bto_ewmult2<3, 0, 3, double>;
template class bto_ewmult2<3, 0, 4, double>;
template class bto_ewmult2<3, 0, 5, double>;
                                          
template class bto_ewmult2<0, 4, 1, double>;
template class bto_ewmult2<0, 4, 2, double>;
template class bto_ewmult2<0, 4, 3, double>;
template class bto_ewmult2<0, 4, 4, double>;
template class bto_ewmult2<1, 3, 1, double>;
template class bto_ewmult2<1, 3, 2, double>;
template class bto_ewmult2<1, 3, 3, double>;
template class bto_ewmult2<1, 3, 4, double>;
template class bto_ewmult2<2, 2, 1, double>;
template class bto_ewmult2<2, 2, 2, double>;
template class bto_ewmult2<2, 2, 3, double>;
template class bto_ewmult2<2, 2, 4, double>;
template class bto_ewmult2<3, 1, 1, double>;
template class bto_ewmult2<3, 1, 2, double>;
template class bto_ewmult2<3, 1, 3, double>;
template class bto_ewmult2<3, 1, 4, double>;
template class bto_ewmult2<4, 0, 1, double>;
template class bto_ewmult2<4, 0, 2, double>;
template class bto_ewmult2<4, 0, 3, double>;
template class bto_ewmult2<4, 0, 4, double>;
                                          
template class bto_ewmult2<0, 5, 1, double>;
template class bto_ewmult2<0, 5, 2, double>;
template class bto_ewmult2<0, 5, 3, double>;
template class bto_ewmult2<1, 4, 1, double>;
template class bto_ewmult2<1, 4, 2, double>;
template class bto_ewmult2<1, 4, 3, double>;
template class bto_ewmult2<2, 3, 1, double>;
template class bto_ewmult2<2, 3, 2, double>;
template class bto_ewmult2<2, 3, 3, double>;
template class bto_ewmult2<3, 2, 1, double>;
template class bto_ewmult2<3, 2, 2, double>;
template class bto_ewmult2<3, 2, 3, double>;
template class bto_ewmult2<4, 1, 1, double>;
template class bto_ewmult2<4, 1, 2, double>;
template class bto_ewmult2<4, 1, 3, double>;
template class bto_ewmult2<5, 0, 1, double>;
template class bto_ewmult2<5, 0, 2, double>;
template class bto_ewmult2<5, 0, 3, double>;
                                          
template class bto_ewmult2<0, 6, 1, double>;
template class bto_ewmult2<0, 6, 2, double>;
template class bto_ewmult2<1, 5, 1, double>;
template class bto_ewmult2<1, 5, 2, double>;
template class bto_ewmult2<2, 4, 1, double>;
template class bto_ewmult2<2, 4, 2, double>;
template class bto_ewmult2<3, 3, 1, double>;
template class bto_ewmult2<3, 3, 2, double>;
template class bto_ewmult2<4, 2, 1, double>;
template class bto_ewmult2<4, 2, 2, double>;
template class bto_ewmult2<5, 1, 1, double>;
template class bto_ewmult2<5, 1, 2, double>;
template class bto_ewmult2<6, 0, 1, double>;
template class bto_ewmult2<6, 0, 2, double>;
                                          
template class bto_ewmult2<0, 7, 1, double>;
template class bto_ewmult2<1, 6, 1, double>;
template class bto_ewmult2<2, 5, 1, double>;
template class bto_ewmult2<3, 4, 1, double>;
template class bto_ewmult2<4, 3, 1, double>;
template class bto_ewmult2<5, 2, 1, double>;
template class bto_ewmult2<6, 1, 1, double>;
template class bto_ewmult2<7, 0, 1, double>;

template class gen_bto_ewmult2< 0, 0, 1, bto_traits<float>, bto_ewmult2<0, 0, 1, float> >;
template class gen_bto_ewmult2< 0, 0, 2, bto_traits<float>, bto_ewmult2<0, 0, 2, float> >;
template class gen_bto_ewmult2< 0, 0, 3, bto_traits<float>, bto_ewmult2<0, 0, 3, float> >;
template class gen_bto_ewmult2< 0, 0, 4, bto_traits<float>, bto_ewmult2<0, 0, 4, float> >;
template class gen_bto_ewmult2< 0, 0, 5, bto_traits<float>, bto_ewmult2<0, 0, 5, float> >;
template class gen_bto_ewmult2< 0, 0, 6, bto_traits<float>, bto_ewmult2<0, 0, 6, float> >;
template class gen_bto_ewmult2< 0, 0, 7, bto_traits<float>, bto_ewmult2<0, 0, 7, float> >;
template class gen_bto_ewmult2< 0, 0, 8, bto_traits<float>, bto_ewmult2<0, 0, 8, float> >;
template class gen_bto_ewmult2< 0, 1, 1, bto_traits<float>, bto_ewmult2<0, 1, 1, float> >;
template class gen_bto_ewmult2< 0, 1, 2, bto_traits<float>, bto_ewmult2<0, 1, 2, float> >;
template class gen_bto_ewmult2< 0, 1, 3, bto_traits<float>, bto_ewmult2<0, 1, 3, float> >;
template class gen_bto_ewmult2< 0, 1, 4, bto_traits<float>, bto_ewmult2<0, 1, 4, float> >;
template class gen_bto_ewmult2< 0, 1, 5, bto_traits<float>, bto_ewmult2<0, 1, 5, float> >;
template class gen_bto_ewmult2< 0, 1, 6, bto_traits<float>, bto_ewmult2<0, 1, 6, float> >;
template class gen_bto_ewmult2< 0, 1, 7, bto_traits<float>, bto_ewmult2<0, 1, 7, float> >;
template class gen_bto_ewmult2< 1, 0, 1, bto_traits<float>, bto_ewmult2<1, 0, 1, float> >;
template class gen_bto_ewmult2< 1, 0, 2, bto_traits<float>, bto_ewmult2<1, 0, 2, float> >;
template class gen_bto_ewmult2< 1, 0, 3, bto_traits<float>, bto_ewmult2<1, 0, 3, float> >;
template class gen_bto_ewmult2< 1, 0, 4, bto_traits<float>, bto_ewmult2<1, 0, 4, float> >;
template class gen_bto_ewmult2< 1, 0, 5, bto_traits<float>, bto_ewmult2<1, 0, 5, float> >;
template class gen_bto_ewmult2< 1, 0, 6, bto_traits<float>, bto_ewmult2<1, 0, 6, float> >;
template class gen_bto_ewmult2< 1, 0, 7, bto_traits<float>, bto_ewmult2<1, 0, 7, float> >;
template class gen_bto_ewmult2< 0, 2, 1, bto_traits<float>, bto_ewmult2<0, 2, 1, float> >;
template class gen_bto_ewmult2< 0, 2, 2, bto_traits<float>, bto_ewmult2<0, 2, 2, float> >;
template class gen_bto_ewmult2< 0, 2, 3, bto_traits<float>, bto_ewmult2<0, 2, 3, float> >;
template class gen_bto_ewmult2< 0, 2, 4, bto_traits<float>, bto_ewmult2<0, 2, 4, float> >;
template class gen_bto_ewmult2< 0, 2, 5, bto_traits<float>, bto_ewmult2<0, 2, 5, float> >;
template class gen_bto_ewmult2< 0, 2, 6, bto_traits<float>, bto_ewmult2<0, 2, 6, float> >;
template class gen_bto_ewmult2< 1, 1, 1, bto_traits<float>, bto_ewmult2<1, 1, 1, float> >;
template class gen_bto_ewmult2< 1, 1, 2, bto_traits<float>, bto_ewmult2<1, 1, 2, float> >;
template class gen_bto_ewmult2< 1, 1, 3, bto_traits<float>, bto_ewmult2<1, 1, 3, float> >;
template class gen_bto_ewmult2< 1, 1, 4, bto_traits<float>, bto_ewmult2<1, 1, 4, float> >;
template class gen_bto_ewmult2< 1, 1, 5, bto_traits<float>, bto_ewmult2<1, 1, 5, float> >;
template class gen_bto_ewmult2< 1, 1, 6, bto_traits<float>, bto_ewmult2<1, 1, 6, float> >;
template class gen_bto_ewmult2< 2, 0, 1, bto_traits<float>, bto_ewmult2<2, 0, 1, float> >;
template class gen_bto_ewmult2< 2, 0, 2, bto_traits<float>, bto_ewmult2<2, 0, 2, float> >;
template class gen_bto_ewmult2< 2, 0, 3, bto_traits<float>, bto_ewmult2<2, 0, 3, float> >;
template class gen_bto_ewmult2< 2, 0, 4, bto_traits<float>, bto_ewmult2<2, 0, 4, float> >;
template class gen_bto_ewmult2< 2, 0, 5, bto_traits<float>, bto_ewmult2<2, 0, 5, float> >;
template class gen_bto_ewmult2< 2, 0, 6, bto_traits<float>, bto_ewmult2<2, 0, 6, float> >;
template class gen_bto_ewmult2< 0, 3, 1, bto_traits<float>, bto_ewmult2<0, 3, 1, float> >;
template class gen_bto_ewmult2< 0, 3, 2, bto_traits<float>, bto_ewmult2<0, 3, 2, float> >;
template class gen_bto_ewmult2< 0, 3, 3, bto_traits<float>, bto_ewmult2<0, 3, 3, float> >;
template class gen_bto_ewmult2< 0, 3, 4, bto_traits<float>, bto_ewmult2<0, 3, 4, float> >;
template class gen_bto_ewmult2< 0, 3, 5, bto_traits<float>, bto_ewmult2<0, 3, 5, float> >;
template class gen_bto_ewmult2< 1, 2, 1, bto_traits<float>, bto_ewmult2<1, 2, 1, float> >;
template class gen_bto_ewmult2< 1, 2, 2, bto_traits<float>, bto_ewmult2<1, 2, 2, float> >;
template class gen_bto_ewmult2< 1, 2, 3, bto_traits<float>, bto_ewmult2<1, 2, 3, float> >;
template class gen_bto_ewmult2< 1, 2, 4, bto_traits<float>, bto_ewmult2<1, 2, 4, float> >;
template class gen_bto_ewmult2< 1, 2, 5, bto_traits<float>, bto_ewmult2<1, 2, 5, float> >;
template class gen_bto_ewmult2< 2, 1, 1, bto_traits<float>, bto_ewmult2<2, 1, 1, float> >;
template class gen_bto_ewmult2< 2, 1, 2, bto_traits<float>, bto_ewmult2<2, 1, 2, float> >;
template class gen_bto_ewmult2< 2, 1, 3, bto_traits<float>, bto_ewmult2<2, 1, 3, float> >;
template class gen_bto_ewmult2< 2, 1, 4, bto_traits<float>, bto_ewmult2<2, 1, 4, float> >;
template class gen_bto_ewmult2< 2, 1, 5, bto_traits<float>, bto_ewmult2<2, 1, 5, float> >;
template class gen_bto_ewmult2< 3, 0, 1, bto_traits<float>, bto_ewmult2<3, 0, 1, float> >;
template class gen_bto_ewmult2< 3, 0, 2, bto_traits<float>, bto_ewmult2<3, 0, 2, float> >;
template class gen_bto_ewmult2< 3, 0, 3, bto_traits<float>, bto_ewmult2<3, 0, 3, float> >;
template class gen_bto_ewmult2< 3, 0, 4, bto_traits<float>, bto_ewmult2<3, 0, 4, float> >;
template class gen_bto_ewmult2< 3, 0, 5, bto_traits<float>, bto_ewmult2<3, 0, 5, float> >;
template class gen_bto_ewmult2< 0, 4, 1, bto_traits<float>, bto_ewmult2<0, 4, 1, float> >;
template class gen_bto_ewmult2< 0, 4, 2, bto_traits<float>, bto_ewmult2<0, 4, 2, float> >;
template class gen_bto_ewmult2< 0, 4, 3, bto_traits<float>, bto_ewmult2<0, 4, 3, float> >;
template class gen_bto_ewmult2< 0, 4, 4, bto_traits<float>, bto_ewmult2<0, 4, 4, float> >;
template class gen_bto_ewmult2< 1, 3, 1, bto_traits<float>, bto_ewmult2<1, 3, 1, float> >;
template class gen_bto_ewmult2< 1, 3, 2, bto_traits<float>, bto_ewmult2<1, 3, 2, float> >;
template class gen_bto_ewmult2< 1, 3, 3, bto_traits<float>, bto_ewmult2<1, 3, 3, float> >;
template class gen_bto_ewmult2< 1, 3, 4, bto_traits<float>, bto_ewmult2<1, 3, 4, float> >;
template class gen_bto_ewmult2< 2, 2, 1, bto_traits<float>, bto_ewmult2<2, 2, 1, float> >;
template class gen_bto_ewmult2< 2, 2, 2, bto_traits<float>, bto_ewmult2<2, 2, 2, float> >;
template class gen_bto_ewmult2< 2, 2, 3, bto_traits<float>, bto_ewmult2<2, 2, 3, float> >;
template class gen_bto_ewmult2< 2, 2, 4, bto_traits<float>, bto_ewmult2<2, 2, 4, float> >;
template class gen_bto_ewmult2< 3, 1, 1, bto_traits<float>, bto_ewmult2<3, 1, 1, float> >;
template class gen_bto_ewmult2< 3, 1, 2, bto_traits<float>, bto_ewmult2<3, 1, 2, float> >;
template class gen_bto_ewmult2< 3, 1, 3, bto_traits<float>, bto_ewmult2<3, 1, 3, float> >;
template class gen_bto_ewmult2< 3, 1, 4, bto_traits<float>, bto_ewmult2<3, 1, 4, float> >;
template class gen_bto_ewmult2< 4, 0, 1, bto_traits<float>, bto_ewmult2<4, 0, 1, float> >;
template class gen_bto_ewmult2< 4, 0, 2, bto_traits<float>, bto_ewmult2<4, 0, 2, float> >;
template class gen_bto_ewmult2< 4, 0, 3, bto_traits<float>, bto_ewmult2<4, 0, 3, float> >;
template class gen_bto_ewmult2< 4, 0, 4, bto_traits<float>, bto_ewmult2<4, 0, 4, float> >;
template class gen_bto_ewmult2< 0, 5, 1, bto_traits<float>, bto_ewmult2<0, 5, 1, float> >;
template class gen_bto_ewmult2< 0, 5, 2, bto_traits<float>, bto_ewmult2<0, 5, 2, float> >;
template class gen_bto_ewmult2< 0, 5, 3, bto_traits<float>, bto_ewmult2<0, 5, 3, float> >;
template class gen_bto_ewmult2< 1, 4, 1, bto_traits<float>, bto_ewmult2<1, 4, 1, float> >;
template class gen_bto_ewmult2< 1, 4, 2, bto_traits<float>, bto_ewmult2<1, 4, 2, float> >;
template class gen_bto_ewmult2< 1, 4, 3, bto_traits<float>, bto_ewmult2<1, 4, 3, float> >;
template class gen_bto_ewmult2< 2, 3, 1, bto_traits<float>, bto_ewmult2<2, 3, 1, float> >;
template class gen_bto_ewmult2< 2, 3, 2, bto_traits<float>, bto_ewmult2<2, 3, 2, float> >;
template class gen_bto_ewmult2< 2, 3, 3, bto_traits<float>, bto_ewmult2<2, 3, 3, float> >;
template class gen_bto_ewmult2< 3, 2, 1, bto_traits<float>, bto_ewmult2<3, 2, 1, float> >;
template class gen_bto_ewmult2< 3, 2, 2, bto_traits<float>, bto_ewmult2<3, 2, 2, float> >;
template class gen_bto_ewmult2< 3, 2, 3, bto_traits<float>, bto_ewmult2<3, 2, 3, float> >;
template class gen_bto_ewmult2< 4, 1, 1, bto_traits<float>, bto_ewmult2<4, 1, 1, float> >;
template class gen_bto_ewmult2< 4, 1, 2, bto_traits<float>, bto_ewmult2<4, 1, 2, float> >;
template class gen_bto_ewmult2< 4, 1, 3, bto_traits<float>, bto_ewmult2<4, 1, 3, float> >;
template class gen_bto_ewmult2< 5, 0, 1, bto_traits<float>, bto_ewmult2<5, 0, 1, float> >;
template class gen_bto_ewmult2< 5, 0, 2, bto_traits<float>, bto_ewmult2<5, 0, 2, float> >;
template class gen_bto_ewmult2< 5, 0, 3, bto_traits<float>, bto_ewmult2<5, 0, 3, float> >;
template class gen_bto_ewmult2< 0, 6, 1, bto_traits<float>, bto_ewmult2<0, 6, 1, float> >;
template class gen_bto_ewmult2< 0, 6, 2, bto_traits<float>, bto_ewmult2<0, 6, 2, float> >;
template class gen_bto_ewmult2< 1, 5, 1, bto_traits<float>, bto_ewmult2<1, 5, 1, float> >;
template class gen_bto_ewmult2< 1, 5, 2, bto_traits<float>, bto_ewmult2<1, 5, 2, float> >;
template class gen_bto_ewmult2< 2, 4, 1, bto_traits<float>, bto_ewmult2<2, 4, 1, float> >;
template class gen_bto_ewmult2< 2, 4, 2, bto_traits<float>, bto_ewmult2<2, 4, 2, float> >;
template class gen_bto_ewmult2< 3, 3, 1, bto_traits<float>, bto_ewmult2<3, 3, 1, float> >;
template class gen_bto_ewmult2< 3, 3, 2, bto_traits<float>, bto_ewmult2<3, 3, 2, float> >;
template class gen_bto_ewmult2< 4, 2, 1, bto_traits<float>, bto_ewmult2<4, 2, 1, float> >;
template class gen_bto_ewmult2< 4, 2, 2, bto_traits<float>, bto_ewmult2<4, 2, 2, float> >;
template class gen_bto_ewmult2< 5, 1, 1, bto_traits<float>, bto_ewmult2<5, 1, 1, float> >;
template class gen_bto_ewmult2< 5, 1, 2, bto_traits<float>, bto_ewmult2<5, 1, 2, float> >;
template class gen_bto_ewmult2< 6, 0, 1, bto_traits<float>, bto_ewmult2<6, 0, 1, float> >;
template class gen_bto_ewmult2< 6, 0, 2, bto_traits<float>, bto_ewmult2<6, 0, 2, float> >;
template class gen_bto_ewmult2< 0, 7, 1, bto_traits<float>, bto_ewmult2<0, 7, 1, float> >;
template class gen_bto_ewmult2< 1, 6, 1, bto_traits<float>, bto_ewmult2<1, 6, 1, float> >;
template class gen_bto_ewmult2< 2, 5, 1, bto_traits<float>, bto_ewmult2<2, 5, 1, float> >;
template class gen_bto_ewmult2< 3, 4, 1, bto_traits<float>, bto_ewmult2<3, 4, 1, float> >;
template class gen_bto_ewmult2< 4, 3, 1, bto_traits<float>, bto_ewmult2<4, 3, 1, float> >;
template class gen_bto_ewmult2< 5, 2, 1, bto_traits<float>, bto_ewmult2<5, 2, 1, float> >;
template class gen_bto_ewmult2< 6, 1, 1, bto_traits<float>, bto_ewmult2<6, 1, 1, float> >;
template class gen_bto_ewmult2< 7, 0, 1, bto_traits<float>, bto_ewmult2<7, 0, 1, float> >;


template class bto_ewmult2<0, 0, 1, float>;
template class bto_ewmult2<0, 0, 2, float>;
template class bto_ewmult2<0, 0, 3, float>;
template class bto_ewmult2<0, 0, 4, float>;
template class bto_ewmult2<0, 0, 5, float>;
template class bto_ewmult2<0, 0, 6, float>;
template class bto_ewmult2<0, 0, 7, float>;
template class bto_ewmult2<0, 0, 8, float>;
template class bto_ewmult2<0, 1, 1, float>;
template class bto_ewmult2<0, 1, 2, float>;
template class bto_ewmult2<0, 1, 3, float>;
template class bto_ewmult2<0, 1, 4, float>;
template class bto_ewmult2<0, 1, 5, float>;
template class bto_ewmult2<0, 1, 6, float>;
template class bto_ewmult2<0, 1, 7, float>;
template class bto_ewmult2<1, 0, 1, float>;
template class bto_ewmult2<1, 0, 2, float>;
template class bto_ewmult2<1, 0, 3, float>;
template class bto_ewmult2<1, 0, 4, float>;
template class bto_ewmult2<1, 0, 5, float>;
template class bto_ewmult2<1, 0, 6, float>;
template class bto_ewmult2<1, 0, 7, float>;
template class bto_ewmult2<0, 2, 1, float>;
template class bto_ewmult2<0, 2, 2, float>;
template class bto_ewmult2<0, 2, 3, float>;
template class bto_ewmult2<0, 2, 4, float>;
template class bto_ewmult2<0, 2, 5, float>;
template class bto_ewmult2<0, 2, 6, float>;
template class bto_ewmult2<1, 1, 1, float>;
template class bto_ewmult2<1, 1, 2, float>;
template class bto_ewmult2<1, 1, 3, float>;
template class bto_ewmult2<1, 1, 4, float>;
template class bto_ewmult2<1, 1, 5, float>;
template class bto_ewmult2<1, 1, 6, float>;
template class bto_ewmult2<2, 0, 1, float>;
template class bto_ewmult2<2, 0, 2, float>;
template class bto_ewmult2<2, 0, 3, float>;
template class bto_ewmult2<2, 0, 4, float>;
template class bto_ewmult2<2, 0, 5, float>;
template class bto_ewmult2<2, 0, 6, float>;
template class bto_ewmult2<0, 3, 1, float>;
template class bto_ewmult2<0, 3, 2, float>;
template class bto_ewmult2<0, 3, 3, float>;
template class bto_ewmult2<0, 3, 4, float>;
template class bto_ewmult2<0, 3, 5, float>;
template class bto_ewmult2<1, 2, 1, float>;
template class bto_ewmult2<1, 2, 2, float>;
template class bto_ewmult2<1, 2, 3, float>;
template class bto_ewmult2<1, 2, 4, float>;
template class bto_ewmult2<1, 2, 5, float>;
template class bto_ewmult2<2, 1, 1, float>;
template class bto_ewmult2<2, 1, 2, float>;
template class bto_ewmult2<2, 1, 3, float>;
template class bto_ewmult2<2, 1, 4, float>;
template class bto_ewmult2<2, 1, 5, float>;
template class bto_ewmult2<3, 0, 1, float>;
template class bto_ewmult2<3, 0, 2, float>;
template class bto_ewmult2<3, 0, 3, float>;
template class bto_ewmult2<3, 0, 4, float>;
template class bto_ewmult2<3, 0, 5, float>;
template class bto_ewmult2<0, 4, 1, float>;
template class bto_ewmult2<0, 4, 2, float>;
template class bto_ewmult2<0, 4, 3, float>;
template class bto_ewmult2<0, 4, 4, float>;
template class bto_ewmult2<1, 3, 1, float>;
template class bto_ewmult2<1, 3, 2, float>;
template class bto_ewmult2<1, 3, 3, float>;
template class bto_ewmult2<1, 3, 4, float>;
template class bto_ewmult2<2, 2, 1, float>;
template class bto_ewmult2<2, 2, 2, float>;
template class bto_ewmult2<2, 2, 3, float>;
template class bto_ewmult2<2, 2, 4, float>;
template class bto_ewmult2<3, 1, 1, float>;
template class bto_ewmult2<3, 1, 2, float>;
template class bto_ewmult2<3, 1, 3, float>;
template class bto_ewmult2<3, 1, 4, float>;
template class bto_ewmult2<4, 0, 1, float>;
template class bto_ewmult2<4, 0, 2, float>;
template class bto_ewmult2<4, 0, 3, float>;
template class bto_ewmult2<4, 0, 4, float>;
template class bto_ewmult2<0, 5, 1, float>;
template class bto_ewmult2<0, 5, 2, float>;
template class bto_ewmult2<0, 5, 3, float>;
template class bto_ewmult2<1, 4, 1, float>;
template class bto_ewmult2<1, 4, 2, float>;
template class bto_ewmult2<1, 4, 3, float>;
template class bto_ewmult2<2, 3, 1, float>;
template class bto_ewmult2<2, 3, 2, float>;
template class bto_ewmult2<2, 3, 3, float>;
template class bto_ewmult2<3, 2, 1, float>;
template class bto_ewmult2<3, 2, 2, float>;
template class bto_ewmult2<3, 2, 3, float>;
template class bto_ewmult2<4, 1, 1, float>;
template class bto_ewmult2<4, 1, 2, float>;
template class bto_ewmult2<4, 1, 3, float>;
template class bto_ewmult2<5, 0, 1, float>;
template class bto_ewmult2<5, 0, 2, float>;
template class bto_ewmult2<5, 0, 3, float>;
template class bto_ewmult2<0, 6, 1, float>;
template class bto_ewmult2<0, 6, 2, float>;
template class bto_ewmult2<1, 5, 1, float>;
template class bto_ewmult2<1, 5, 2, float>;
template class bto_ewmult2<2, 4, 1, float>;
template class bto_ewmult2<2, 4, 2, float>;
template class bto_ewmult2<3, 3, 1, float>;
template class bto_ewmult2<3, 3, 2, float>;
template class bto_ewmult2<4, 2, 1, float>;
template class bto_ewmult2<4, 2, 2, float>;
template class bto_ewmult2<5, 1, 1, float>;
template class bto_ewmult2<5, 1, 2, float>;
template class bto_ewmult2<6, 0, 1, float>;
template class bto_ewmult2<6, 0, 2, float>;
template class bto_ewmult2<0, 7, 1, float>;
template class bto_ewmult2<1, 6, 1, float>;
template class bto_ewmult2<2, 5, 1, float>;
template class bto_ewmult2<3, 4, 1, float>;
template class bto_ewmult2<4, 3, 1, float>;
template class bto_ewmult2<5, 2, 1, float>;
template class bto_ewmult2<6, 1, 1, float>;
template class bto_ewmult2<7, 0, 1, float>;

} // namespace libtensor
