set(CBLAS_FOUND FALSE)

find_path(CBLAS_INCLUDE_PATH cblas.h)

if(CBLAS_INCLUDE_PATH)

set(CBLAS_FOUND TRUE)

set(CBLAS_LIBRARIES blas)

if(NOT CBLAS_FIND_QUIETLY)
	message(STATUS "Found CBLAS: " ${CBLAS_INCLUDE_PATH})
endif(NOT CBLAS_FIND_QUIETLY)

endif(CBLAS_INCLUDE_PATH)

